global:
  chartName: express
express:
  # Deployment object
  deployment:
    enabled: true
    name: express
    namespace: express
    replicas: 1
    appName: express
    role: api
    containerName: nodejs-app
    imageRepository: eleazarharold/express-node
    imageTag: "v4"
    port: 3000
  # Updated (New) Deployment resource
  newDeployment:
    enabled: false
  # Canary Service object
  canaryService:
    enabled: false
  # Service object
  service:
    enabled: true
    name: express-service
    namespace: express
    appName: express
    type: LoadBalancer
    servicePort: 3000
    targetPort: 3000
  # Service Account object
  serviceAccount:
    enabled: true
    name: express-service-account
    namespace: express
  # Namespace object
  namespace:
    enabled: true
    name: express
  # Ingress object
  ingress:
    enabled: false
  # Horizontal Pod Autoscaler
  hpa:
    enabled: false
  # Canary Rollout
  canaryRollout:
    enabled: false
  # Virtual Service
  virtualService:
    enabled: true
    name: express-virtual-service
    namespace: express
    destination:
      host: express-service
      port: 3000
