apiVersion: v2
description: A Common Helm Chart for Digital Platform Applications
keywords:
- platform
maintainers:
- email: outlier.developer@gmail.com
  name: Luke Mwila
name: platform
version: 0.1.0
