{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.virtualService.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - asm-ingress/asm-ingress-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Values.virtualService.destination.host }}
        port:
          number: {{ .Values.virtualService.destination.port }}
    retries:
      attempts: 3
      perTryTimeout: 2s
{{- end }}