---
apiVersion: v2
description: The fastapi microservice helm chart
keywords:
  - fastapi
maintainers:
  - name: eleazar yewa harold
    email: eleazar.yewa@zenbusiness.com
name: fastapi
appVersion: "0.1.0"
version: 0.1.0
dependencies:
  - name: platform
    repository: file://../../platform
    version: 0.1.0
    alias: fastapi
